package testcases.CWE80_XSS.s01;

import javax.servlet.http.*;

public class ServletMain extends HttpServlet {

    private static final long serialVersionUID = 1L; /* needed since Servlets are serializable */


    public void doPost(HttpServletRequest request, HttpServletResponse response) {
        doGet(request, response);
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response) {
        doGetCWE1(request, response);
        doGetCWE2(request, response);
        doGetCWE3(request, response);
        doGetCWE4(request, response);
        doGetCWE5(request, response);
        doGetCWE6(request, response);
        doGetCWE7(request, response);
        doGetCWE8(request, response);
        doGetCWE9(request, response);
    }

    private static void doGetCWE1(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-1 */
            (new testcases.CWE80_XSS.s01.J21139()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21138()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21063()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21062()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21215()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21214()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21165()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21164()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J20973()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J20972()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21319()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21318()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21127()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21126()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21177()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21176()).runTest(request, response);
            /* END-AUTOGENERATED-SERVLET-TESTS-1 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE1 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE2(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-2 */

            /* END-AUTOGENERATED-SERVLET-TESTS-2 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE2 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE3(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-3 */

            /* END-AUTOGENERATED-SERVLET-TESTS-3 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE3 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE4(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-4 */

            /* END-AUTOGENERATED-SERVLET-TESTS-4 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE4 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE5(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-5 */

            /* END-AUTOGENERATED-SERVLET-TESTS-5 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE5 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {

                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE6(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-6 */

            /* END-AUTOGENERATED-SERVLET-TESTS-6 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE6 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE7(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-7 */

            /* END-AUTOGENERATED-SERVLET-TESTS-7 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE7 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE8(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-8 */
            (new testcases.CWE80_XSS.s01.J21139()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21138()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21601()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21600()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21063()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21062()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21215()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21214()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21165()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21164()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21573()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21572()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J20973()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J20972()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21461()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21460()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21319()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21318()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21647()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21646()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21127()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21126()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21523()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21522()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21177()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21176()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21499()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21498()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21363()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21362()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21443()).runTest(request, response);
            (new testcases.CWE80_XSS.s01.J21442()).runTest(request, response);
            /* END-AUTOGENERATED-SERVLET-TESTS-8 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE8 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }

    private static void doGetCWE9(HttpServletRequest request, HttpServletResponse response) {
        try {
            /* BEGIN-AUTOGENERATED-SERVLET-TESTS-9 */

            /* END-AUTOGENERATED-SERVLET-TESTS-9 */
        } catch (Throwable t) {

            /* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
             * and write to the console (since we can't write to the response without possibly throwing another exception)
             */

            System.out.println(
                    " Caught thowable from doGetCWE9 ");

            System.out.println(" Throwable's message = " + t.getMessage());

            System.out.println("Stack trace below");

            StackTraceElement stes[] = t.getStackTrace();

            for (StackTraceElement ste : stes) {
                System.out.println("  " + ste.toString());
            }
        }
    }
}

